import { BankInfo, RecommendedBundle } from '../types';

export const INITIAL_BANKS: BankInfo[] = [
  {
    id: 'cbe',
    abbreviation: 'CBE',
    displayName: 'CBE',
    fullName: 'Commercial Bank of Ethiopia',
    senderIds: ['889', '847', 'CBE'],
    ussd: '*889#',
    color: 'from-purple-600 to-indigo-700',
    accentColor: '#9333ea',
    enabled: true,
    currentBalance: 14850.50,
  },
  {
    id: 'telebirr',
    abbreviation: 'TELEBIRR',
    displayName: 'Telebirr',
    fullName: 'Telebirr SuperApp',
    senderIds: ['127', 'TELEBIRR'],
    ussd: '*127#',
    color: 'from-amber-500 to-yellow-600',
    accentColor: '#eab308',
    enabled: true,
    currentBalance: 4250.75,
  },
  {
    id: 'cbebirr',
    abbreviation: 'CBEBIRR',
    displayName: 'CBEBirr',
    fullName: 'CBEBirr Mobile Money',
    senderIds: ['CBEBirr', 'CBEBIRR'],
    ussd: '*847#',
    color: 'from-fuchsia-600 to-pink-700',
    accentColor: '#d946ef',
    enabled: true,
    currentBalance: 1200.00,
  },
  {
    id: 'awash',
    abbreviation: 'AWASH',
    displayName: 'Awash Bank',
    fullName: 'Awash International Bank',
    senderIds: ['901', 'Awash', 'AwashBank', 'Awash Bank'],
    ussd: '*901#',
    color: 'from-blue-600 to-cyan-700',
    accentColor: '#2563eb',
    enabled: true,
    currentBalance: 8750.25,
  },
  {
    id: 'dashen',
    abbreviation: 'DASHEN',
    displayName: 'Dashen Bank',
    fullName: 'Dashen Bank / Amole',
    senderIds: ['996', '675', 'Dashen', 'DashenBank'],
    ussd: '*996#',
    color: 'from-emerald-600 to-teal-700',
    accentColor: '#059669',
    enabled: true,
    currentBalance: 6120.00,
  },
  {
    id: 'boa',
    abbreviation: 'BOA',
    displayName: 'Bank of Abyssinia',
    fullName: 'Bank of Abyssinia',
    senderIds: ['815', '999', 'BOA', 'Abyssinia', 'AbyssiniaBank'],
    ussd: '*815#',
    color: 'from-amber-600 to-orange-700',
    accentColor: '#ea580c',
    enabled: true,
    currentBalance: 3450.15,
  },
  {
    id: 'coop',
    abbreviation: 'COOP',
    displayName: 'Coopbank',
    fullName: 'Cooperative Bank of Oromia',
    senderIds: ['841', '896', 'Coop', 'Coopbank'],
    ussd: '*841#',
    color: 'from-lime-600 to-emerald-700',
    accentColor: '#65a30d',
    enabled: true,
    currentBalance: 2900.00,
  },
  {
    id: 'hibret',
    abbreviation: 'HIBRET',
    displayName: 'Hibret Bank',
    fullName: 'Hibret Bank',
    senderIds: ['811', 'Hibret', 'HibretBank'],
    ussd: '*811#',
    color: 'from-rose-600 to-red-700',
    accentColor: '#e11d48',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'wegagen',
    abbreviation: 'WEGAGEN',
    displayName: 'Wegagen Bank',
    fullName: 'Wegagen Bank',
    senderIds: ['866', 'Wegagen', 'WegagenBank'],
    ussd: '*866#',
    color: 'from-orange-600 to-amber-700',
    accentColor: '#d97706',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'nib',
    abbreviation: 'NIB',
    displayName: 'NIB Bank',
    fullName: 'Nib International Bank',
    senderIds: ['865', 'NIB', 'NIBBank'],
    ussd: '*865#',
    color: 'from-sky-600 to-blue-700',
    accentColor: '#0284c7',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'bunna',
    abbreviation: 'BUNNA',
    displayName: 'Bunna Bank',
    fullName: 'Bunna International Bank',
    senderIds: ['820', 'Bunna', 'BunnaBank'],
    ussd: '*820#',
    color: 'from-amber-700 to-yellow-800',
    accentColor: '#b45309',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'zemen',
    abbreviation: 'ZEMEN',
    displayName: 'Zemen Bank',
    fullName: 'Zemen Bank',
    senderIds: ['844', 'Zemen', 'ZemenBank'],
    ussd: '*844#',
    color: 'from-cyan-600 to-teal-700',
    accentColor: '#0891b2',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'berhan',
    abbreviation: 'BERHAN',
    displayName: 'Berhan Bank',
    fullName: 'Berhan Bank',
    senderIds: ['881', 'Berhan', 'BerhanBank'],
    ussd: '*881#',
    color: 'from-yellow-600 to-orange-700',
    accentColor: '#ca8a04',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'enat',
    abbreviation: 'ENAT',
    displayName: 'Enat Bank',
    fullName: 'Enat Bank',
    senderIds: ['845', 'Enat', 'EnatBank'],
    ussd: '*845#',
    color: 'from-pink-600 to-rose-700',
    accentColor: '#db2777',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'siinqee',
    abbreviation: 'SIINQEE',
    displayName: 'Siinqee Bank',
    fullName: 'Siinqee Bank',
    senderIds: ['871', 'Siinqee', 'SiinqeeBank'],
    ussd: '*871#',
    color: 'from-emerald-700 to-green-800',
    accentColor: '#047857',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'amhara',
    abbreviation: 'AMHARA',
    displayName: 'Amhara Bank',
    fullName: 'Amhara Bank',
    senderIds: ['690', 'Amhara', 'AmharaBank'],
    ussd: '*690#',
    color: 'from-blue-700 to-indigo-800',
    accentColor: '#1d4ed8',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'lion',
    abbreviation: 'LION',
    displayName: 'Lion Bank',
    fullName: 'Lion International Bank',
    senderIds: ['801', 'Lion', 'LionBank'],
    ussd: '*801#',
    color: 'from-yellow-700 to-amber-800',
    accentColor: '#a16207',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'oromia',
    abbreviation: 'OROMIA',
    displayName: 'Oromia Bank',
    fullName: 'Oromia Bank',
    senderIds: ['840', 'Oromia', 'OromiaBank'],
    ussd: '*840#',
    color: 'from-green-600 to-teal-800',
    accentColor: '#16a34a',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'global',
    abbreviation: 'GLOBAL',
    displayName: 'Global Bank',
    fullName: 'Global Bank Ethiopia',
    senderIds: ['8027', '9335', 'GBE', 'Global', 'GlobalBank'],
    ussd: '*8027#',
    color: 'from-indigo-600 to-blue-800',
    accentColor: '#4f46e5',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'ahadu',
    abbreviation: 'AHADU',
    displayName: 'Ahadu Bank',
    fullName: 'Ahadu Bank',
    senderIds: ['611', 'Ahadu', 'AhaduBank'],
    ussd: '*611#',
    color: 'from-violet-600 to-purple-800',
    accentColor: '#7c3aed',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'zamzam',
    abbreviation: 'ZAMZAM',
    displayName: 'ZamZam Bank',
    fullName: 'ZamZam Bank (Interest Free)',
    senderIds: ['600', 'ZamZam', 'ZamZamBank'],
    ussd: '*600#',
    color: 'from-teal-600 to-emerald-800',
    accentColor: '#0d9488',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'hijra',
    abbreviation: 'HIJRA',
    displayName: 'Hijra Bank',
    fullName: 'Hijra Bank (Interest Free)',
    senderIds: ['827', 'Hijra', 'HijraBank'],
    ussd: '*827#',
    color: 'from-emerald-600 to-green-700',
    accentColor: '#059669',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'tsehay',
    abbreviation: 'TSEHAY',
    displayName: 'Tsehay Bank',
    fullName: 'Tsehay Bank',
    senderIds: ['921', 'Tsehay', 'TsehayBank'],
    ussd: '*921#',
    color: 'from-amber-500 to-yellow-600',
    accentColor: '#d97706',
    enabled: false,
    currentBalance: 0,
  },
  {
    id: 'acsi',
    abbreviation: 'ACSI',
    displayName: 'ACSI',
    fullName: 'Amhara Credit and Saving Institution',
    senderIds: ['ACSI', 'ACSIBank'],
    ussd: '*690#',
    color: 'from-slate-600 to-slate-800',
    accentColor: '#475569',
    enabled: false,
    currentBalance: 0,
  },
];

export const RECOMMENDED_BUNDLES: RecommendedBundle[] = [
  {
    id: 'monthly-data-1',
    title: '5GB Monthly Internet',
    type: 'internet',
    duration: 'monthly',
    amount: 5,
    unit: 'GB',
    priceEtb: 100,
    ussdCode: '*999*1*1*4*1#',
    popular: true,
  },
  {
    id: 'monthly-data-2',
    title: '15GB Monthly Internet',
    type: 'internet',
    duration: 'monthly',
    amount: 15,
    unit: 'GB',
    priceEtb: 250,
    ussdCode: '*999*1*1*4*2#',
  },
  {
    id: 'weekly-data-1',
    title: '1GB Daily Internet',
    type: 'internet',
    duration: 'daily',
    amount: 1,
    unit: 'GB',
    priceEtb: 30,
    ussdCode: '*999*1*1*1*2#',
  },
  {
    id: 'night-data-1',
    title: '10GB Night Internet (11pm-6am)',
    type: 'internet',
    duration: 'night',
    amount: 10,
    unit: 'GB',
    priceEtb: 50,
    ussdCode: '*999*1*1*5*1#',
  },
  {
    id: 'weekly-voice-1',
    title: '100 Min Weekly Voice',
    type: 'voice',
    duration: 'weekly',
    amount: 100,
    unit: 'MIN',
    priceEtb: 50,
    ussdCode: '*999*1*2*2*1#',
    popular: true,
  },
  {
    id: 'monthly-voice-1',
    title: '300 Min Monthly Voice',
    type: 'voice',
    duration: 'monthly',
    amount: 300,
    unit: 'MIN',
    priceEtb: 130,
    ussdCode: '*999*1*2*4*1#',
  },
  {
    id: 'sms-pack-1',
    title: '200 Weekly SMS',
    type: 'sms',
    duration: 'weekly',
    amount: 200,
    unit: 'SMS',
    priceEtb: 20,
    ussdCode: '*999*1*3*2*1#',
  },
];
