build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

naming:
  FunctionNaming:
    active: false
  FunctionParameterNaming:
    active: false
  MatchingDeclarationName:
    active: false

complexity:
  CyclomaticComplexMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  LongMethod:
    active: false
  NestedBlockDepth:
    active: false
  ComplexCondition:
    active: false

style:
  MaxLineLength:
    active: false
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  UnusedPrivateMember:
    active: false
  UnusedParameter:
    active: false
  UnusedPrivateProperty:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  MayBeConst:
    active: false

potential-bugs:
  ImplicitDefaultLocale:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
